name: .NET Core Desktop

on:
    push:
    workflow_dispatch:
        inputs:
            logLevel:
                description: "Log level"
                required: true
                default: "warning"
                type: choice
                options:
                    - info
                    - warning
                    - debug
            tags:
                description: "Test scenario tags"
                required: false
                type: boolean
            environment:
                description: "Environment to run tests against"
                type: environment
                required: false

jobs:
    build:
        strategy:
            matrix:
                configuration:
                    [Debug, Release]
                    # configuration: [Debug]

        runs-on: self-hosted # For a list of available runner types, refer to

        env:
            Solution_Name: FullApp3.sln # Replace with your solution name, i.e. MyWpfApp.sln.
            Test_Project_Path: FullApp3.Modules.TimeCard.Tests.csproj # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
            Wap_Project_Directory: your-wap-project-directory-name # Replace with the Wap project directory relative to the solution, i.e. MyWpfApp.Package.
            Wap_Project_Path: your-wap-project-path # Replace with the path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.

        steps:
            # - name: Checkout
            #   uses: actions/checkout@v4
            #   with:
            #       fetch-depth: 0

            # - name: powershell allow...
            #   shell: cmd
            #   run: powershell -Command "Set-ExecutionPolicy RemoteSigned -Scope CurrentUser"
            # - name: check powershell version
            #   run: $host.Version

            - name: disp home
              run: |
                  wsl bash -c "pwd"
                  wsl bash -c "ls"

            # Install the .NET Core workload
            - name: Install .NET Core
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 8.0.x

            # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
            - name: Setup MSBuild.exe
              uses: microsoft/setup-msbuild@v2
            - name: Build app using dotnet msbuild
              run: dotnet msbuild ./FullApp3/FullApp3/FullApp3.csproj -t:Rebuild -p:Configuration=Release

            - name: Publish WPF App
              run: dotnet publish ./FullApp3/FullApp3/FullApp3.csproj -c Release -o ./FullApp3/PublishOutput

            - name: Run E2E test (FlaUI)
              # run: dotnet test FullApp3/Tests/FullApp3.Modules.ModuleName.Tests/FullApp3.Modules.TimeCard.Tests.csproj --configuration Release
              run: dotnet test FullApp3\Tests\FullApp3.Modules.ModuleName.Tests\FullApp3.Modules.TimeCard.Tests.csproj
#
#
