name: main
on: push
jobs:
  bra1:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: echo "Windowsでビルド"
      - run: |
          ls -a
          echo "" 
          git branch -a
