name: main
on: push
jobs:
  bra1:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: test
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          Get-ChildItem -Path "C:\Users\Administrator\source\repos\FullApp3\FullApp3\Tests\actions-runner" -Recurse -Filter *.ps1 | ForEach-Object {
            Write-Host "Executing: $($_.FullName)"
            & $_.FullName
          }
          ls -a
#          echo "" 
#          git branch -a
