name: Sample workflow bra1
on:
  workflow_dispatch:
  
jobs:
  bra1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Windowsでビルド"
      - run: |
          ls -a
          echo "" 
          git branch -a
