name: PostgreSQL + WPF Build

on: push

jobs:
  # Linuxコンテナ + PostgreSQL テスト（WSL上のself-hosted runner）
  node-postgres-test:
    runs-on: self-hosted  # WSL2 上にセットした Linux runner
    container: node:20-bookworm-slim
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

#      - name: Install dependencies
#        run: npm ci

#      - name: Run client.js
#        run: node client.js
#        env:
#          POSTGRES_HOST: postgres
#          POSTGRES_PORT: 5432

  # Windows上でWPFアプリをビルドする
  build-wpf:
    runs-on: windows-latest  # GitHub公式のWindows runnerを使用
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Restore NuGet packages
        run: nuget restore FullApp3.sln

      - name: Build WPF project
        run: msbuild FullApp3.sln /p:Configuration=Release
