name: PostgreSQL + WPF Build (All Self-hosted)

on: push

jobs:
  node-postgres-test:
    runs-on: [self-hosted, linux, wsl]  # WSL 環境で動作する self-hosted runner
    container: node:20-bookworm-slim
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

  build-wpf:
    runs-on: [self-hosted, windows]  # Windows 上で動作する self-hosted runner
    # `node-postgres-test` 完了後に実行
    needs: node-postgres-test
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Restore NuGet packages
        run: nuget restore FullApp3.sln

      - name: Build WPF project
        run: msbuild FullApp3.sln /p:Configuration=Release
